### ISSUE TITLE
Can't play encrypted video

### ISSUE THREAD

**Issue by ladeng** [smmousavi8872/MMPlayer#5]
When I play the encrypted video, I get an exception

This is my code for encrypting the video：
<pre>
private void encryptFile() {
        File inputFile = new File("/storage/emulated/0/9846.mp4");
        File outputFile = new File(path+ "/storage/emulated/0/a/v/test_pkcs5.v");
        DataSink fileDataSink = new CustomFileDataSink(outputFile);
        DataSink customAesCipherDataSink = new CustomAesCipherDataSink(AES_KEY.getBytes(),AES_IV.getBytes()
                , fileDataSink);

        try (InputStream inputStream = new FileInputStream(inputFile)) {
            DataSpec dataSpec = new DataSpec(Uri.fromFile(outputFile));
            customAesCipherDataSink.open(dataSpec);
            byte[] buffer = new byte[4096];
            int bytesRead;
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                customAesCipherDataSink.write(buffer, 0, bytesRead);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                customAesCipherDataSink.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
</pre>

CustomAesCipherDataSink.java:
<pre>
public final class CustomAesCipherDataSink implements DataSink {
    private final byte[] aesKey;
    private final byte[] aesIv;
    private final DataSink wrappedDataSink;
    private CipherOutputStream cipherOutputStream;

    public CustomAesCipherDataSink(byte[] aesKey, byte[] aesIv, DataSink wrappedDataSink) {
        this.aesKey = aesKey;
        this.aesIv = aesIv;
        this.wrappedDataSink = wrappedDataSink;
    }

    @Override
    public void open(DataSpec dataSpec) throws IOException {
        wrappedDataSink.open(dataSpec);
        try {
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            SecretKeySpec secretKeySpec = new SecretKeySpec(aesKey, "AES");
            IvParameterSpec ivParameterSpec = new IvParameterSpec(aesIv);
            cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, ivParameterSpec);

            cipherOutputStream = new CipherOutputStream(((CustomFileDataSink) wrappedDataSink).getOutputStream(), cipher);
        } catch (Exception e) {
            throw new IOException("Failed to initialize AES cipher", e);
        }
    }

    @Override
    public void write(byte[] buffer, int offset, int length) throws IOException {
        if (cipherOutputStream != null) {
            cipherOutputStream.write(buffer, offset, length);
        } else {
            throw new IOException("CipherOutputStream is not initialized.");
        }
    }

    @Override
    public void close() throws IOException {
        if (cipherOutputStream != null) {
            cipherOutputStream.close();
            cipherOutputStream = null;
        }
        wrappedDataSink.close();
    }
}
</pre>

⭐️Some code copied from your project, please note that I use "AES/CBC/PKCS5Padding" for encryption and decryption：

FileCipherInputStream.java:
<pre>
class FileCipherInputStream(
    private val upstream: FileInputStream,
    private var cipher: Cipher,
    private val secretKeySpec: SecretKeySpec,
    private val ivParameterSpec: IvParameterSpec? = null,
) : CipherInputStream(upstream, cipher) {

    // in case of other modes with IV, use this method
    fun forceIvSkip(bytesToSkip: Long): Long {
        val skipped: Long = upstream.skip(bytesToSkip)
        try {
            val skipOverFlow = (bytesToSkip % cipher.blockSize).toInt()
            val skipBlockPosition = bytesToSkip - skipOverFlow
            val blocksNumber = skipBlockPosition / cipher.blockSize
            val ivOffset = BigInteger(1, ivParameterSpec!!.iv).add(
                BigInteger.valueOf(blocksNumber)
            )
            val ivOffsetBytes = ivOffset.toByteArray()
            val skippedIvSpec = if (ivOffsetBytes.size < cipher.blockSize) {
                val resizedIvOffsetBytes = ByteArray(cipher.blockSize)
                System.arraycopy(
                    ivOffsetBytes,
                    0,
                    resizedIvOffsetBytes,
                    cipher.blockSize - ivOffsetBytes.size,
                    ivOffsetBytes.size
                )
                IvParameterSpec(resizedIvOffsetBytes)
            } else {
                IvParameterSpec(
                    ivOffsetBytes,
                    ivOffsetBytes.size - cipher.blockSize,
                    cipher.blockSize
                )
            }

            cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, skippedIvSpec)
            val skipBuffer = ByteArray(skipOverFlow)
            cipher.update(skipBuffer, 0, skipOverFlow, skipBuffer)
        } catch (e: java.lang.Exception) {
            e.printStackTrace()
            return 0
        }
        return skipped
    }

    @Throws(IOException::class)
    override fun available(): Int {
        return upstream.available()
    }
}
</pre>

FileEncryptedDataSource.java:
<pre>
@UnstableApi
class FileEncryptedDataSource(private val key: ByteArray, private val iv: ByteArray) : DataSource {

    private var encryptedFileStream: FileInputStream? = null
    private var cipherInputStream: FileCipherInputStream? = null
    private var bytesToRead: Long = 0
    private var bytesRead: Int = 0
    private var isOpen = false
    private var dataSpec: DataSpec? = null

    @Throws(IOException::class)
    override fun open(dataSpec: DataSpec): Long {
        this.dataSpec = dataSpec
        if (isOpen) return bytesToRead
        try {
            setupCipherInputStream()
            cipherInputStream?.forceIvSkip(dataSpec.position)

            if (dataSpec.length != C.LENGTH_UNSET.toLong()) {
                bytesToRead = dataSpec.length
                return bytesToRead
            }
            if (bytesToRead == Int.MAX_VALUE.toLong()) {
                bytesToRead = C.LENGTH_UNSET.toLong()
                return bytesToRead
            }
            bytesToRead = cipherInputStream!!.available().toLong()
        } catch (e: IOException) {
            throw IOException(e)
        }
        isOpen = true
        return bytesToRead
    }

    @SuppressLint("GetInstance")
    private fun setupCipherInputStream() {
        //
        val path = uri?.path ?: throw RuntimeException("Path cann't be empty!")
        encryptedFileStream = File(path).inputStream()
        val keySpec = SecretKeySpec(
            key, // use you won byte array key
            "AES", //use your own alg.
        )
        // if you are using ECB mode, it is not required.
        val ivParameterSpec = IvParameterSpec(
            iv, // ues you own iv key
        )
        val cipher = Cipher.getInstance(
            "AES/CBC/PKCS5Padding" // use your own mode.
        )
        cipherInputStream = FileCipherInputStream(
            encryptedFileStream!!,
            cipher,
            keySpec,
            ivParameterSpec,// if you are using ECB, remove this line.
        )
    }

    @Throws(IOException::class)
    override fun read(buffer: ByteArray, offset: Int, readLength: Int): Int {
        if (bytesToRead == 0L) {
            return C.RESULT_END_OF_INPUT
        }

        bytesRead = try {
            cipherInputStream!!.read(buffer, offset, readLength)
        } catch (e: IOException) {
            throw IOException(e)
        }

        if (bytesRead < 0) {
            if (bytesToRead != C.LENGTH_UNSET.toLong())
                throw IOException(EOFException())
            return C.RESULT_END_OF_INPUT
        }

        if (bytesToRead != C.LENGTH_UNSET.toLong())
            bytesToRead -= bytesRead
        return bytesRead
    }

    override fun addTransferListener(transferListener: TransferListener) {}

    override fun getUri(): Uri? = dataSpec?.uri

    @Throws(IOException::class)
    override fun close() {
        try {
            encryptedFileStream?.close()
            cipherInputStream?.close()
        } catch (e: IOException) {
            throw IOException(e)
        } finally {
            if (isOpen) {
                isOpen = false
            }
        }
    }
}
</pre>

FileEncryptedDataSourceFactory.java:
<pre>
@UnstableApi
class FileEncryptedDataSourceFactory( private val key: ByteArray,
                                         private val iv: ByteArray) : DataSource.Factory {
    override fun createDataSource(): DataSource = FileEncryptedDataSource(key,iv)
}
</pre>

player initialization code:
<pre>
MediaItem item = new MediaItem.Builder()
                    .setMimeType(MimeTypes.BASE_TYPE_VIDEO)
                    .setUri(Uri.fromFile(cacheFile))
                    .build();
            DataSource.Factory dataSourceFactory  = new FileEncryptedDataSourceFactory(AES_KEY.getBytes(),AES_IV.getBytes());
            MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(item);
            player.setMediaSource(mediaSource);
            player.prepare();
</pre>

after initialization, I get an exception:
<pre>
Playback error
androidx.media3.exoplayer.ExoPlaybackException: Source error
  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:706)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:219)
  at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor, AvifExtractor) could read the stream.{contentIsMalformed=false, dataType=1}
  at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:108)
  at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1060)
  at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
</pre>

When I use the original method to play the video, it can be played normally, but I can't use player.seekto(), so I tried your code: https://medium.com/@s.m.mousavi1993/how-to-play-an-aes-encrypted-audio-video-from-a-local-file-and-a-remote-server-on-android-part-1-c7a841daf0e0

Now I don't know why I can't load the encrypted video using your method. Please help me solve the problem. Thank you！

**Comment by ladeng** [comment]
I understand!
When I change the video encryption and decryption method to "AES/ECB/PKCS5Padding" and use cipherInputStream?.forceSkip(dataSpec.position) in the open method of FileEncryptedDataSource, the encrypted video can be initialized, but using seekto will get this exception:
<pre>
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:706)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:219)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: androidx.media3.common.ParserException: Invalid NAL length{contentIsMalformed=true, dataType=1}
      at androidx.media3.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:725)
      at androidx.media3.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:332)
      at androidx.media3.exoplayer.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:147)
      at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1082)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
</pre>

Now there are two questions:
1. Why can't I initialize the video using "AES/CBC/PKCS5Padding"?
2. Why can't I seek to?

I think the inability to seek to is a key problem! Because I haven't found a solution for a long time...

**Comment by MohsenNaderzadeh** [comment]
CBC Mode is not suitable for playing videos or medias because of how this algorithm work.
